# Generated by Django 4.2.5 on 2023-09-26 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_elective_seme_studentdata_sem_subjects_sem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subjects',
            name='dept',
        ),
        migrations.AlterField(
            model_name='elective',
            name='seme',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='sem',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='sem',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('sems', models.IntegerField(blank=True, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept')),
            ],
        ),
        migrations.AddField(
            model_name='subjects',
            name='cor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
            preserve_default=False,
        ),
    ]
