# Generated by Django 4.2.5 on 2023-09-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_remove_subjects_dept_alter_elective_seme_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elective',
            name='dept',
        ),
        migrations.AddField(
            model_name='elective',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_table',
            name='course',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='home.course'),
            preserve_default=False,
        ),
    ]
