# Generated by Django 4.2.1 on 2023-09-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_elective_dept_elective_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='time_table',
            old_name='Time',
            new_name='from_time',
        ),
        migrations.AddField(
            model_name='time_table',
            name='sem',
            field=models.IntegerField(blank=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='time_table',
            name='to_time',
            field=models.TimeField(default=None),
            preserve_default=False,
        ),
    ]
