# Generated by Django 4.2.1 on 2023-09-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_room_status_eligibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='eligibility',
            name='cor',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
