# Generated by Django 4.2.1 on 2023-10-01 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_eligibility_cor'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_staff',
            name='status',
            field=models.BooleanField(blank=True, default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
