# Generated by Django 4.2.1 on 2023-10-01 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_student_seat_cour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject_student_link',
            name='stu',
        ),
        migrations.RemoveField(
            model_name='subject_student_link',
            name='sub',
        ),
        migrations.RemoveField(
            model_name='student_data',
            name='elective',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='types',
        ),
        migrations.DeleteModel(
            name='Elective',
        ),
        migrations.DeleteModel(
            name='Subject_Student_link',
        ),
    ]
