# Generated by Django 4.2.1 on 2023-10-01 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_subject_student_link_stu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_staff',
            name='mail',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
