# Generated by Django 4.2.1 on 2023-10-04 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_remove_add_staff_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_staff',
            name='uid',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
