# Generated by Django 4.2.1 on 2023-10-04 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0030_add_staff_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_staff',
            name='status',
        ),
        migrations.RemoveField(
            model_name='add_staff',
            name='uid',
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(blank=True, default=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.dept')),
                ('uid', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
